export const experienceCards = [
  { experience: {
      id: 'cf0b8676-b868-453b-b7f9-227e2e4620eb',
      name: 'Nutrition Session',
      description: 'Good nutrition is one of the keys to a healthy life. You can improve your health by keeping a balanced diet. You should eat foods that contain vitamins and minerals. This includes fruits, vegetables, whole grains, dairy, and a source of protein.',
      duration: '60',
      link: '/',
      price: '200',
      cover_url: 'https://imagedelivery.net/uDbEDRBQqhBXrrfuCRrATQ/709188d3-b05c-4c51-34af-4fba5d5b9b00/public',
    },
    host: {
      first_name: 'Julian',
      last_name: 'Clatro',
      avatar_url: 'https://imagedelivery.net/uDbEDRBQqhBXrrfuCRrATQ/c51df920-788c-4d25-1a45-61a3f812a300/public'
    }
  },
  { experience: {
      id: 'cf0b8676-b868-453b-b7f9-227e2e4620eb',
      name: 'Streching',
      description: 'Good nutrition is one of the keys to a healthy life. You can improve your health by keeping a balanced diet. You should eat foods that contain vitamins and minerals. This includes fruits, vegetables, whole grains, dairy, and a source of protein.',
      duration: '60',
      link: '/',
      price: '200',
      cover_url: 'https://imagedelivery.net/uDbEDRBQqhBXrrfuCRrATQ/b79a8d58-a0a2-4f08-0e50-7301c430a600/public',
    },
    host: {
      first_name: 'Julian',
      last_name: 'Clatro',
      avatar_url: 'https://imagedelivery.net/uDbEDRBQqhBXrrfuCRrATQ/c51df920-788c-4d25-1a45-61a3f812a300/public'
    }
  },
  { experience: {
      id: 'cf0b8676-b868-453b-b7f9-227e2e4620eb',
      name: 'Karate',
      description: 'Good nutrition is one of the keys to a healthy life. You can improve your health by keeping a balanced diet. You should eat foods that contain vitamins and minerals. This includes fruits, vegetables, whole grains, dairy, and a source of protein.',
      duration: '60',
      link: '/',
      price: '200',
      cover_url: 'https://imagedelivery.net/uDbEDRBQqhBXrrfuCRrATQ/da39aa34-399d-4ca3-b66c-520d63440800/public',
    },
    host: {
      first_name: 'Julian',
      last_name: 'Clatro',
      avatar_url: 'https://imagedelivery.net/uDbEDRBQqhBXrrfuCRrATQ/c51df920-788c-4d25-1a45-61a3f812a300/public'
    }
  },
  { experience: {
      id: 'cf0b8676-b868-453b-b7f9-227e2e4620eb',
      name: 'Roller',
      description: 'Good nutrition is one of the keys to a healthy life. You can improve your health by keeping a balanced diet. You should eat foods that contain vitamins and minerals. This includes fruits, vegetables, whole grains, dairy, and a source of protein.',
      duration: '60',
      link: '/',
      price: '200',
      cover_url: 'https://imagedelivery.net/uDbEDRBQqhBXrrfuCRrATQ/6f826245-a115-4e6a-5a6b-4b2390ed2800/public',
    },
    host: {
      first_name: 'Julian',
      last_name: 'Clatro',
      avatar_url: 'https://imagedelivery.net/uDbEDRBQqhBXrrfuCRrATQ/c51df920-788c-4d25-1a45-61a3f812a300/public'
    }
  },
  { experience: {
      id: 'cf0b8676-b868-453b-b7f9-227e2e4620eb',
      name: 'Yoga',
      description: 'Good nutrition is one of the keys to a healthy life. You can improve your health by keeping a balanced diet. You should eat foods that contain vitamins and minerals. This includes fruits, vegetables, whole grains, dairy, and a source of protein.',
      duration: '60',
      link: '/',
      price: '200',
      cover_url: 'https://imagedelivery.net/uDbEDRBQqhBXrrfuCRrATQ/44f7537b-f33e-4b18-9aea-78e9f476d200/public',
    },
    host: {
      first_name: 'Julian',
      last_name: 'Clatro',
      avatar_url: 'https://imagedelivery.net/uDbEDRBQqhBXrrfuCRrATQ/c51df920-788c-4d25-1a45-61a3f812a300/public'
    }
  },
  { experience: {
      id: 'cf0b8676-b868-453b-b7f9-227e2e4620eb',
      name: 'Street Bike',
      description: 'Good nutrition is one of the keys to a healthy life. You can improve your health by keeping a balanced diet. You should eat foods that contain vitamins and minerals. This includes fruits, vegetables, whole grains, dairy, and a source of protein.',
      duration: '60',
      link: '/',
      price: '200',
      cover_url: 'https://imagedelivery.net/uDbEDRBQqhBXrrfuCRrATQ/0a3fa27e-456f-4879-4f3e-006f340c6500/public',
    },
    host: {
      first_name: 'Julian',
      last_name: 'Clatro',
      avatar_url: 'https://imagedelivery.net/uDbEDRBQqhBXrrfuCRrATQ/c51df920-788c-4d25-1a45-61a3f812a300/public'
    }
  },
  { experience: {
      id: 'cf0b8676-b868-453b-b7f9-227e2e4620eb',
      name: 'Skate',
      description: 'Good nutrition is one of the keys to a healthy life. You can improve your health by keeping a balanced diet. You should eat foods that contain vitamins and minerals. This includes fruits, vegetables, whole grains, dairy, and a source of protein.',
      duration: '60',
      link: '/',
      price: '200',
      cover_url: 'https://imagedelivery.net/uDbEDRBQqhBXrrfuCRrATQ/f4f08a47-f609-4ece-b541-4bccd3551800/public',
    },
    host: {
      first_name: 'Julian',
      last_name: 'Clatro',
      avatar_url: 'https://imagedelivery.net/uDbEDRBQqhBXrrfuCRrATQ/c51df920-788c-4d25-1a45-61a3f812a300/public'
    }
  },
  { experience: {
      id: 'cf0b8676-b868-453b-b7f9-227e2e4620eb',
      name: '8',
      description: 'Good nutrition is one of the keys to a healthy life. You can improve your health by keeping a balanced diet. You should eat foods that contain vitamins and minerals. This includes fruits, vegetables, whole grains, dairy, and a source of protein.',
      duration: '60',
      link: '/',
      price: '200',
      cover_url: 'https://imagedelivery.net/uDbEDRBQqhBXrrfuCRrATQ/709188d3-b05c-4c51-34af-4fba5d5b9b00/public',
    },
    host: {
      first_name: 'Julian',
      last_name: 'Clatro',
      avatar_url: 'https://imagedelivery.net/uDbEDRBQqhBXrrfuCRrATQ/c51df920-788c-4d25-1a45-61a3f812a300/public'
    }
  }
]

export const languages_list = [
  {name:"Afrikaans", code:"af"},
  {name:"Albanian - shqip", code:"sq"},
  {name:"Amharic - አማርኛ", code:"am"},
  {name:"Arabic - العربية", code:"ar"},
  {name:"Aragonese - aragonés", code:"an"},
  {name:"Armenian - հայերեն", code:"hy"},
  {name:"Asturian - asturianu", code:"ast"},
  {name:"Azerbaijani - azərbaycan dili", code:"az"},
  {name:"Basque - euskara", code:"eu"},
  {name:"Belarusian - беларуская", code:"be"},
  {name:"Bengali - বাংলা", code:"bn"},
  {name:"Bosnian - bosanski", code:"bs"},
  {name:"Breton - brezhoneg", code:"br"},
  {name:"Bulgarian - български", code:"bg"},
  {name:"Catalan - català", code:"ca"},
  {name:"Central Kurdish - کوردی (دەستنوسی عەرەبی)", code:"ckb"},
  {name:"Chinese - 中文", code:"zh"},
  {name:"Chinese (Hong Kong) - 中文（香港）", code:"zh-HK"},
  {name:"Chinese (Simplified) - 中文（简体）", code:"zh-CN"},
  {name:"Chinese (Traditional) - 中文（繁體）", code:"zh-TW"},
  {name:"Corsican", code:"co"},
  {name:"Croatian - hrvatski", code:"hr"},
  {name:"Czech - čeština", code:"cs"},
  {name:"Danish - dansk", code:"da"},
  {name:"Dutch - Nederlands", code:"nl"},
  {name:"English", code:"en"},
  {name:"Esperanto - esperanto", code:"eo"},
  {name:"Estonian - eesti", code:"et"},
  {name:"Faroese - føroyskt", code:"fo"},
  {name:"Filipino", code:"fil"},
  {name:"Finnish - suomi", code:"fi"},
  {name:"French - français", code:"fr"},
  {name:"Galician - galego", code:"gl"},
  {name:"Georgian - ქართული", code:"ka"},
  {name:"German - Deutsch", code:"de"},
  {name:"Greek - Ελληνικά", code:"el"},
  {name:"Guarani", code:"gn"},
  {name:"Gujarati - ગુજરાતી", code:"gu"},
  {name:"Hausa", code:"ha"},
  {name:"Hawaiian - ʻŌlelo Hawaiʻi", code:"haw"},
  {name:"Hebrew - עברית", code:"he"},
  {name:"Hindi - हिन्दी", code:"hi"},
  {name:"Hungarian - magyar", code:"hu"},
  {name:"Icelandic - íslenska", code:"is"},
  {name:"Indonesian - Indonesia", code:"id"},
  {name:"Interlingua", code:"ia"},
  {name:"Irish - Gaeilge", code:"ga"},
  {name:"Italian - italiano", code:"it"},
  {name:"Japanese - 日本語", code:"ja"},
  {name:"Kannada - ಕನ್ನಡ", code:"kn"},
  {name:"Kazakh - қазақ тілі", code:"kk"},
  {name:"Khmer - ខ្មែរ", code:"km"},
  {name:"Korean - 한국어", code:"ko"},
  {name:"Kurdish - Kurdî", code:"ku"},
  {name:"Kyrgyz - кыргызча", code:"ky"},
  {name:"Lao - ລາວ", code:"lo"},
  {name:"Latin", code:"la"},
  {name:"Latvian - latviešu", code:"lv"},
  {name:"Lingala - lingála", code:"ln"},
  {name:"Lithuanian - lietuvių", code:"lt"},
  {name:"Macedonian - македонски", code:"mk"},
  {name:"Malay - Bahasa Melayu", code:"ms"},
  {name:"Malayalam - മലയാളം", code:"ml"},
  {name:"Maltese - Malti", code:"mt"},
  {name:"Marathi - मराठी", code:"mr"},
  {name:"Mongolian - монгол", code:"mn"},
  {name:"Nepali - नेपाली", code:"ne"},
  {name:"Norwegian - norsk", code:"no"},
  {name:"Norwegian Bokmål - norsk bokmål", code:"nb"},
  {name:"Norwegian Nynorsk - nynorsk", code:"nn"},
  {name:"Occitan", code:"oc"},
  {name:"Oriya - ଓଡ଼ିଆ", code:"or"},
  {name:"Oromo - Oromoo", code:"om"},
  {name:"Pashto - پښتو", code:"ps"},
  {name:"Persian - فارسی", code:"fa"},
  {name:"Polish - polski", code:"pl"},
  {name:"Portuguese - português", code:"pt"},
  {name:"Punjabi - ਪੰਜਾਬੀ", code:"pa"},
  {name:"Quechua", code:"qu"},
  {name:"Romanian - română", code:"ro"},
  {name:"Romanian (Moldova) - română (Moldova)", code:"mo"},
  {name:"Romansh - rumantsch", code:"rm"},
  {name:"Russian - русский", code:"ru"},
  {name:"Scottish Gaelic", code:"gd"},
  {name:"Serbian - српски", code:"sr"},
  {name:"Serbo - Croatian", code:"sh"},
  {name:"Shona - chiShona", code:"sn"},
  {name:"Sindhi", code:"sd"},
  {name:"Sinhala - සිංහල", code:"si"},
  {name:"Slovak - slovenčina", code:"sk"},
  {name:"Slovenian - slovenščina", code:"sl"},
  {name:"Somali - Soomaali", code:"so"},
  {name:"Southern Sotho", code:"st"},
  {name:"Spanish - español", code:"es"},
  {name:"Sundanese", code:"su"},
  {name:"Swahili - Kiswahili", code:"sw"},
  {name:"Swedish - svenska", code:"sv"},
  {name:"Tajik - тоҷикӣ", code:"tg"},
  {name:"Tamil - தமிழ்", code:"ta"},
  {name:"Tatar", code:"tt"},
  {name:"Telugu - తెలుగు", code:"te"},
  {name:"Thai - ไทย", code:"th"},
  {name:"Tigrinya - ትግርኛ", code:"ti"},
  {name:"Tongan - lea fakatonga", code:"to"},
  {name:"Turkish - Türkçe", code:"tr"},
  {name:"Turkmen", code:"tk"},
  {name:"Twi", code:"tw"},
  {name:"Ukrainian - українська", code:"uk"},
  {name:"Urdu - اردو", code:"ur"},
  {name:"Uyghur", code:"ug"},
  {name:"Uzbek - o‘zbek", code:"uz"},
  {name:"Vietnamese - Tiếng Việt", code:"vi"},
  {name:"Walloon - wa", code:"wa"},
  {name:"Welsh - Cymraeg", code:"cy"},
  {name:"Western Frisian", code:"fy"},
  {name:"Xhosa", code:"xh"},
  {name:"Yiddish", code:"yi"},
  {name:"Yoruba - Èdè Yorùbá", code:"yo"},
  {name:"Zulu - isiZulu", code:"zu"}
];